# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ff48c64cbd1e12e1a158fdd35464cd209f95d56ab19658991368a4c73f60549ed547caacc5f606fac0cab095d0f8550686e98f347debee0c4a04a95fc7c7eb

test:
  secret_key_base: cd9856c6f5d921f16996d1fdee10ceb626f4484c5bc386f3721dc3c54ac16336b198ecdf08726573147cdcb794adae15b912dabcd8afd7c09e7240d4f07b2407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
